"""empty message

Revision ID: 34e68b6e2c51
Revises: 
Create Date: 2019-04-20 15:42:57.991591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e68b6e2c51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('busid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('numchekins', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('numreviews', sa.Integer(), nullable=True),
    sa.Column('avgrating', sa.Float(), nullable=True),
    sa.Column('isopen', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longtitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('busid')
    )
    op.create_table('yelpuser',
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avgstar', sa.String(), nullable=True),
    sa.Column('usersince', sa.String(), nullable=True),
    sa.Column('fans', sa.Integer(), nullable=True),
    sa.Column('cool', sa.Integer(), nullable=True),
    sa.Column('funny', sa.Integer(), nullable=True),
    sa.Column('useful', sa.Integer(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.String(), nullable=True),
    sa.Column('longtitude', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('attribute',
    sa.Column('busid', sa.String(), nullable=False),
    sa.Column('attribute_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['busid'], ['business.busid'], ),
    sa.PrimaryKeyConstraint('busid', 'attribute_name')
    )
    op.create_table('category',
    sa.Column('busid', sa.String(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['busid'], ['business.busid'], ),
    sa.PrimaryKeyConstraint('busid', 'category_name')
    )
    op.create_table('checkin',
    sa.Column('busid', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('hour', sa.String(), nullable=False),
    sa.Column('numcheck', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busid'], ['business.busid'], ),
    sa.PrimaryKeyConstraint('busid', 'day', 'hour')
    )
    op.create_table('friends',
    sa.Column('friendsid', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['friendsid'], ['yelpuser.userid'], ),
    sa.ForeignKeyConstraint(['userid'], ['yelpuser.userid'], ),
    sa.PrimaryKeyConstraint('friendsid', 'userid')
    )
    op.create_table('hours',
    sa.Column('busid', sa.String(), nullable=False),
    sa.Column('day', sa.String(), nullable=False),
    sa.Column('openclose', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['busid'], ['business.busid'], ),
    sa.PrimaryKeyConstraint('busid', 'day', 'openclose')
    )
    op.create_table('review',
    sa.Column('reviewid', sa.String(), nullable=False),
    sa.Column('busid', sa.String(), nullable=False),
    sa.Column('userid', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('useful', sa.Integer(), nullable=True),
    sa.Column('funny', sa.Integer(), nullable=True),
    sa.Column('cool', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busid'], ['business.busid'], ),
    sa.ForeignKeyConstraint(['userid'], ['yelpuser.userid'], ),
    sa.PrimaryKeyConstraint('reviewid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('hours')
    op.drop_table('friends')
    op.drop_table('checkin')
    op.drop_table('category')
    op.drop_table('attribute')
    op.drop_table('yelpuser')
    op.drop_table('business')
    # ### end Alembic commands ###
