"""empty message

Revision ID: b719e1db8ec7
Revises: e76b3608ea94
Create Date: 2019-04-20 15:45:43.004888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b719e1db8ec7'
down_revision = 'e76b3608ea94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('numcheckins', sa.Integer(), nullable=True))
    op.drop_column('business', 'numchekins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('numchekins', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('business', 'numcheckins')
    # ### end Alembic commands ###
