"""empty message

Revision ID: e76b3608ea94
Revises: 34e68b6e2c51
Create Date: 2019-04-20 15:43:36.122183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e76b3608ea94'
down_revision = '34e68b6e2c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business', sa.Column('longitude', sa.String(), nullable=True))
    op.drop_column('business', 'longtitude')
    op.add_column('yelpuser', sa.Column('longitude', sa.String(), nullable=True))
    op.drop_column('yelpuser', 'longtitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yelpuser', sa.Column('longtitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('yelpuser', 'longitude')
    op.add_column('business', sa.Column('longtitude', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('business', 'longitude')
    # ### end Alembic commands ###
